name: dask-mpi-dev
dependencies:
  - dask
  - distributed
  - mpich
  - mpi4py
  - versioneer
  - pytest
  - pytest-cov
  - coverage
  - requests
  - pip:
    - git+git://github.com/dask/distributed.git