version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-2.7
      - test-3.6

jobs:

  test-2.7:
    docker:
      - image: continuumio/miniconda:latest
    environment:
      PYTHON: "2.7"
      ENV_NAME: "dask-mpi-dev"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "ci/environment-dev-2.7.yml" }}
      - run:
          name: Install and activate conda environment
          command: ./ci/install-circle.sh
      - run:
          name: Running tests
          command: |
            source activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ dask_mpi/tests/
      - save_cache:
          key: deps-{{ .Branch }}-2.7-{{ checksum "ci/environment-dev-2.7.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

  test-3.6:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "dask-mpi-dev"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "ci/environment-dev-3.6.yml" }}
      - run:
          name: Install and activate conda environment
          command: ./ci/install-circle.sh
      - run:
          name: Running tests
          command: |
            source activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ dask_mpi/tests/
      - save_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "ci/environment-dev-3.6.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
      - run:
          name: Code Coverage
          command: |
            source activate ${ENV_NAME}

            echo "[Uploading Coverage]"
            codecov