version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-2.7
          filters:
            branches:
              only:
                - master

steps-initial: &steps-initial
  - run: apk add --no-cache build-base ca-certificates git openssh bash curl
  - checkout
  - restore_cache:
      keys:
        - conda-pkgs

steps-final: &steps-final
  - run: source activate dask-mpi-dev && pip install --no-deps -e .
  - save_cache:
      key: conda-pkgs
      paths:
        - /opt/conda/pkgs
  - run:
      name: Running tests
      command: |
        source activate dask-mpi-dev
        pytest --junitxml=test-reports/junit.xml --cov=./ dask_mpi/tests/
  - run:
       name: Coverage
       command: source activate dask-mpi-dev && codecov
       when: on_success

jobs:
  test-2.7:
    docker:
      - image: frolvlad/alpine-miniconda3
    steps:
      - *steps-initial
      - run: conda create -q -n dask-mpi-dev python=2.7 && conda env update -f environment-dev.yml --prune
      - *steps-final
