version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-2.7-mpich
      - test-2.7-openmpi
      - test-3.6-mpich
      - test-3.6-openmpi

jobs:

  test-2.7-mpich:
    docker:
      - image: condaforge/linux-anvil:latest
       
    environment:
      PYTHON: "2.7"
      ENV_NAME: "dask-mpi-dev"
      MPI: "mpich"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-2.7-mpich-{{ checksum "ci/environment-dev-2.7-mpich.yml" }}
      - run:
          name: Install and activate conda environment
          command: ./ci/install-circle.sh
      - run:
          name: Running tests
          command: |
            conda activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ dask_mpi/tests/ --verbose
      - save_cache:
          key: deps-{{ .Branch }}-2.7-mpich-{{ checksum "ci/environment-dev-2.7-mpich.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

  test-2.7-openmpi:
    docker:
      - image: condaforge/linux-anvil:latest

    environment:
      PYTHON: "2.7"
      ENV_NAME: "dask-mpi-dev"
      MPI: "openmpi"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-2.7-openmpi-{{ checksum "ci/environment-dev-2.7-openmpi.yml" }}
      - run:
          name: Install and activate conda environment
          command: ./ci/install-circle.sh
      - run:
          name: Running tests
          command: |
            conda activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ dask_mpi/tests/ --verbose
      - save_cache:
          key: deps-{{ .Branch }}-2.7-openmpi-{{ checksum "ci/environment-dev-2.7-openmpi.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

  test-3.6-mpich:
    docker:
      - image: condaforge/linux-anvil:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "dask-mpi-dev"
      MPI: "mpich"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-mpich-{{ checksum "ci/environment-dev-3.6-mpich.yml" }}
      - run:
          name: Install and activate conda environment
          command: ./ci/install-circle.sh
      - run:
          name: Running tests
          command: |
            conda activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ dask_mpi/tests/ --verbose
      - save_cache:
          key: deps-{{ .Branch }}-3.6-mpich-{{ checksum "ci/environment-dev-3.6-mpich.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
      - run:
          name: Code Coverage
          command: |
            conda activate ${ENV_NAME}

            echo "[Uploading Coverage]"
            codecov

  test-3.6-openmpi:
    docker:
      - image: condaforge/linux-anvil:latest
    user: openmpi

    environment:
      PYTHON: "3.6"
      ENV_NAME: "dask-mpi-dev"
      MPI: "openmpi"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-openmpi-{{ checksum "ci/environment-dev-3.6-openmpi.yml" }}
      - run:
          name: Install and activate conda environment
          command: ./ci/install-circle.sh
      - run:
          name: Running tests
          command: |
            conda activate ${ENV_NAME}
            pytest --junitxml=test-reports/junit.xml --cov=./ dask_mpi/tests/ --verbose
      - save_cache:
          key: deps-{{ .Branch }}-3.6-openmpi-{{ checksum "ci/environment-dev-3.6-openmpi.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
  