name: dask-mpi-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - dask
  - distributed
  - mpich
  - mpi4py
  - versioneer
  - pytest
  - pytest-cov
  - coverage
  - requests
