name: dask-mpi-docs
dependencies:
  - dask
  - distributed
  - mpich
  - mpi4py
  - versioneer
  - sphinx
  - pygments
  - pip:
    - git+https://github.com/dask/distributed.git
    - dask_sphinx_theme
    - numpydoc
    - sphinx-click
